sylius_grid:
    grids:
        app_admin_supplier:
            driver:
                options:
                    class: "%app.model.supplier.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                email:
                    type: string
                    label: sylius.ui.email
